spring.application.name=hermes
server.port = 8191
server.servlet.context-path=/hermes/

bh.inbound.url = https://agentic.intics.ai/alchemy-server/alchemy/api/v2/transaction/create/pipeline/fileUrl
ph.inbound.url = https://intics.elevance.ngrok.dev/alchemy-server/alchemy/api/v2/transaction/create/pipeline/fileUrl

bh.shadow.inbound.url = https://agentic.intics.ai/alchemy-server/alchemy/api/v2/transaction/create/pipeline/shadow/fileUrl
ph.shadow.inbound.url = https://intics.elevance.ngrok.dev/alchemy-server/alchemy/api/v2/transaction/create/pipeline/shadow/fileUrl

bh.login.url = https://agentic.intics.ai/alchemy-server/alchemy/api/v2/auth/login
ph.login.url = https://intics.elevance.ngrok.dev/alchemy-server/alchemy/api/v2/auth/login

login.source=PH

# Health check
#management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.health.elasticsearch.enabled=false